name: Format

on:
  push:
    branches:

jobs:
  format:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install packages
        run: pnpm install

      - name: Run format
        run: pnpm run format

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Format by GitHub Actions
